// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_CRUD_practice1.Domain.Entity;

public partial class Accounting
{
    public int accountingId { get; set; }

    public int memberId { get; set; }

    public int typeId { get; set; }

    public string message { get; set; }

    public decimal money { get; set; }

    public DateTime recordTime { get; set; }

    public DateTime timestamp { get; set; }
}