// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_CRUD_practice1.Domain.Entity;

public partial class Member
{
    public int memberId { get; set; }

    public string name { get; set; }

    public string phone { get; set; }

    public string email { get; set; }

    public string password { get; set; }
}