// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_CRUD_practice1.Domain.Entity;

public partial class Type
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid typeId { get; set; }

    /// <summary>
    /// 類別標籤名稱
    /// </summary>
    public string typeName { get; set; }
}